{-
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
-}

--Infinite Fibonacci series starting with 1 
fibs = 1 : 2 : zipWith (+) fibs (tail fibs)
--fib = 1 : 2 : [ a + b | (a, b) <- zip fib (tail fib)] --another way to get it

--Answer
ans = sum $ filter even $ takeWhile (< 4* 10^6) fibs
